// itineraryPdf — renders an itinerary's markdown into a styled PDF and shares it.
// Uses expo-print (HTML -> PDF) + expo-sharing. Mirrors the PWA PDF download.
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const TEAL = '#2EC4B6';

// Minimal, safe markdown -> HTML (headings, bold, lists, paragraphs).
function mdToHtml(md: string): string {
  const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const lines = (md || '').split('\n');
  let html = '';
  let inList = false;
  const closeList = () => { if (inList) { html += '</ul>'; inList = false; } };

  for (let raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) { closeList(); continue; }
    // bold inline
    const inline = (s: string) =>
      esc(s).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/\*(.+?)\*/g, '<em>$1</em>');

    if (/^#\s/.test(line)) { closeList(); html += `<h1>${inline(line.replace(/^#\s/, ''))}</h1>`; }
    else if (/^##\s/.test(line)) { closeList(); html += `<h2>${inline(line.replace(/^##\s/, ''))}</h2>`; }
    else if (/^###\s/.test(line)) { closeList(); html += `<h3>${inline(line.replace(/^###\s/, ''))}</h3>`; }
    else if (/^[-*]\s/.test(line)) {
      if (!inList) { html += '<ul>'; inList = true; }
      html += `<li>${inline(line.replace(/^[-*]\s/, ''))}</li>`;
    } else { closeList(); html += `<p>${inline(line)}</p>`; }
  }
  closeList();
  return html;
}

export async function downloadItineraryPdf(opts: {
  markdown: string;
  title: string;
  destination: string;
  duration: string;
}): Promise<{ ok: boolean; error?: string }> {
  try {
    const body = mdToHtml(opts.markdown);
    const html = `
      <html><head><meta name="viewport" content="width=device-width, initial-scale=1" />
      <style>
        * { font-family: -apple-system, Roboto, Helvetica, sans-serif; }
        body { padding: 28px; color: #1f2937; line-height: 1.55; }
        .cover { background: linear-gradient(135deg, ${TEAL}, #14B8A6); color: #fff; padding: 28px; border-radius: 16px; margin-bottom: 24px; }
        .cover h1 { color: #fff; margin: 0 0 6px; font-size: 26px; }
        .cover p { color: rgba(255,255,255,.9); margin: 0; font-size: 14px; }
        h1 { font-size: 22px; color: #111827; margin-top: 24px; }
        h2 { font-size: 18px; color: ${TEAL}; margin-top: 20px; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; }
        h3 { font-size: 15px; color: #374151; margin-top: 14px; }
        p { font-size: 13px; margin: 8px 0; }
        ul { margin: 8px 0; padding-left: 20px; }
        li { font-size: 13px; margin: 4px 0; }
        .footer { margin-top: 32px; text-align: center; color: #9ca3af; font-size: 11px; }
      </style></head>
      <body>
        <div class="cover">
          <h1>${opts.title}</h1>
          <p>${opts.duration}-day trip to ${opts.destination} · Powered by Prayana AI</p>
        </div>
        ${body}
        <div class="footer">Generated by Prayana AI · prayanaai.com</div>
      </body></html>`;

    const { uri } = await Print.printToFileAsync({ html });
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: opts.title, UTI: 'com.adobe.pdf' });
    }
    return { ok: true };
  } catch (e: any) {
    console.warn('[itineraryPdf] failed:', e?.message);
    return { ok: false, error: e?.message };
  }
}
